<?php

namespace Database\Seeders;

use App\Models\Font;
use Illuminate\Database\Seeder;

class FontSeeder extends Seeder
{
    public function run(): void
    {
        if (Font::count() > 0) {
            $this->command->warn('Fonts table is not empty — skipping seeder.');

            return;
        }

        $total = 0;

        foreach (static::fonts() as $font) {
            Font::create($font);
            $total++;
        }

        $this->command->info("Seeded {$total} fonts.");
    }

    /**
     * @return list<array<string, mixed>>
     */
    private static function fonts(): array
    {
        return [
            [
                'name' => 'font-inter',
                'title' => 'Inter',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'Inter Variable', sans-serif",
                'font_provider' => 'google',
                'font_import' => 'Inter',
                'font_variable' => '--font-inter',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource-variable/inter',
            ],
            [
                'name' => 'font-nerko-one',
                'title' => 'Nerko One',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'Nerko One', cursive",
                'font_provider' => 'google',
                'font_import' => 'NerkoOne',
                'font_variable' => '--font-nerko-one',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource/nerko-one',
            ],
            [
                'name' => 'font-great-vibes',
                'title' => 'Great Vibes',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'Great Vibes', cursive",
                'font_provider' => 'google',
                'font_import' => 'GreatVibes',
                'font_variable' => '--font-great-vibes',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource/great-vibes',
            ],
            [
                'name' => 'font-poppins',
                'title' => 'Poppins',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'Poppins', sans-serif",
                'font_provider' => 'google',
                'font_import' => 'Poppins',
                'font_variable' => '--font-poppins',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource/poppins',
            ],
            [
                'name' => 'font-dm-serif-display',
                'title' => 'DM Serif Display',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'DM Serif Display', serif",
                'font_provider' => 'google',
                'font_import' => 'DMSerifDisplay',
                'font_variable' => '--font-dm-serif-display',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource/dm-serif-display',
            ],
            [
                'name' => 'font-fira-mono',
                'title' => 'Fira Mono',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'Fira Mono', monospace",
                'font_provider' => 'google',
                'font_import' => 'FiraMono',
                'font_variable' => '--font-fira-mono',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource/fira-mono',
            ],
            [
                'name' => 'font-bebas-neue',
                'title' => 'Bebas Neue',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'Bebas Neue', sans-serif",
                'font_provider' => 'google',
                'font_import' => 'BebasNeue',
                'font_variable' => '--font-bebas-neue',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource/bebas-neue',
            ],
            [
                'name' => 'font-playfair-display',
                'title' => 'Playfair Display',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'Playfair Display Variable', sans-serif",
                'font_provider' => 'google',
                'font_import' => 'PlayfairDisplay',
                'font_variable' => '--font-playfair-display-serif',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource-variable/playfair-display',
            ],
            [
                'name' => 'font-caveat',
                'title' => 'Caveat',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'Caveat Variable', cursive",
                'font_provider' => 'google',
                'font_import' => 'Caveat',
                'font_variable' => '--font-caveat',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource-variable/caveat',
            ],
            [
                'name' => 'font-pixelify-sans',
                'title' => 'Pixelify Sans',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'Pixelify Sans Variable', system-ui",
                'font_provider' => 'google',
                'font_import' => 'Pixelify Sans',
                'font_variable' => '--font-pixelify-sans',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource-variable/pixelify-sans',
            ],
            [
                'name' => 'font-orbitron',
                'title' => 'Orbitron',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'Orbitron', sans-serif",
                'font_provider' => 'google',
                'font_import' => 'Orbitron',
                'font_variable' => '--font-orbitron-serif',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource/orbitron',
            ],
            [
                'name' => 'font-ibm-plex-sans',
                'title' => 'IBM Plex Sans',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'IBM Plex Sans', sans-serif",
                'font_provider' => 'google',
                'font_import' => 'IBM Plex Sans',
                'font_variable' => '--font-ibm-plex-sans',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource/ibm-plex-sans',
            ],
            [
                'name' => 'font-ibm-plex-mono',
                'title' => 'IBM Plex Mono',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'IBM Plex Mono', monospace",
                'font_provider' => 'google',
                'font_import' => 'IBM Plex Mono',
                'font_variable' => '--font-ibm-plex-mono',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource/ibm-plex-mono',
            ],
            [
                'name' => 'font-roboto-slab',
                'title' => 'Roboto Slab',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'Roboto Slab', serif",
                'font_provider' => 'google',
                'font_import' => 'Roboto Slab',
                'font_variable' => '--font-roboto-slab',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource/roboto-slab',
            ],
            [
                'name' => 'font-roboto',
                'title' => 'Roboto',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'Roboto Variable', sans-serif",
                'font_provider' => 'google',
                'font_import' => 'Roboto Slab',
                'font_variable' => '--font-roboto',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource-variable/roboto',
            ],
            [
                'name' => 'font-work-sans',
                'title' => 'Work Sans',
                'type' => 'registry:font',
                'author' => 'designbycode',
                'meta' => ['category' => 'fonts', 'version' => '1.0.0'],
                'registryDependencies' => [],
                'font_family' => "'Work Sans Variable', sans-serif",
                'font_provider' => 'google',
                'font_import' => 'WorkSans',
                'font_variable' => '--font-work-sans',
                'font_weight' => [],
                'font_subsets' => ['latin'],
                'font_selector' => null,
                'font_dependency' => '@fontsource-variable/work-sans',
            ],
        ];
    }
}
