import type { RegistryFile, RegistryCssVars, Tag } from '@/types/registry';

export type Theme = {
    name: string;
    title: string;
    description: string | null;
    author: string | null;
    dependencies: string[];
    devDependencies: string[];
    registryDependencies: string[];
    files: RegistryFile[];
    css: Record<string, unknown>[];
    css_base: Record<string, unknown>[];
    tailwind: Record<string, unknown>[];
    cssVars?: RegistryCssVars;
    vars_theme: Record<string, string>;
    vars_light: Record<string, string>;
    vars_dark: Record<string, string>;
    font_family: string | null;
    font_mono: string | null;
    font_serif: string | null;
    font_provider: string | null;
    font_import: string | null;
    font_variable: string | null;
    font_weight: string[];
    font_subsets: string[];
    font_selector: string | null;
    font_dependency: string | null;
    meta: Record<string, unknown>;
    docs: string | null;
    tags?: Tag[] | string[];
    extends: string | null;
    style: string | null;
    icon_library: string | null;
    base_color: string | null;
    theme_config: Record<string, unknown>;
    created_at: string;
    updated_at: string;
};
